# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f99d06ed14e44c0d4b283eb373d2334d9ca9da4f7988d82f19bfa6b72fae2667c7b548db54ad62b930957404afa9d8aeaf7ece093bae3b432f090f38ae1d6507

test:
  secret_key_base: 62594f6ff4f8ba813c5cf45a3d33aec8d73caad8bf11ed2ed5819fec49ffd1786d2c913196b032a6f6d8642323159d5e7e26b7422c515b9d2a3d11a39969d97f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
